version: '3.7'
services:
  db:
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - system_net
    env_file:
      - .env
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
      - ./data/mysql:/var/lib/mysql
networks:
  system_net:
    name: system_net
    driver: bridge
